pipeline { 
agent any 
    stages { 
        stage ('Build') { 
	        steps {
	        	dir("JenkinsTest") {
			        sh "mvn --batch-mode -V -U -e install -Dsurefire.useFile=false"
	        	}
 
        	}
        }
        stage ('Test') { 
	        steps {
	        	dir("JenkinsTest") {
			        sh "mvn --batch-mode -V -U -e test -Dsurefire.useFile=false"
	        	}
			}	 
			
			post {
                always {
                	dir("JenkinsTest") {
	                 // Note that the output from this can be accessed via the Jenkins interface under test results and is associated with the job
                   	 junit 'target/surefire-reports/*.xml'
                   	}
                }
            }       
        }
        stage ('QA') { 
        	steps {
	        	sh "echo qa"
        	}
        }

        stage ('Deploy') { 
    		steps {
	        	sh "echo deploy"
    		}
        }
    }           
 }