pipeline { 
agent any 
    stages { 
        stage ('Build') { 
        	sh "echo build"
        }
        stage ('Test') { 
        	sh "echo test"
        
        }
        stage ('QA') { 
        	sh "echo qa"
        }

        stage ('Deploy') { 
        	sh "echo deploy"
        }

        stage ('Monitor') { 
        	sh "echo monitor"
 
        }
 
    }           
 }