pipeline { 
agent any 
    stages { 
        stage ('Build') { 
	        steps {
    	    	sh "echo build"
        	}
        }
        stage ('Test') { 
	        steps {
	        	sh "echo test"
	        }
        
        }
        stage ('QA') { 
        	steps {
	        	sh "echo qa"
        	}
        }

        stage ('Deploy') { 
    		steps {
	        	sh "echo deploy"
    		}
        }
    }           
 }